using SysCol = System.Collections.Generic;

namespace ChaosFramework.Input.OpenTk
{
    public partial class OpenTkKeyboard
    {
        partial class Key
        {
            static readonly SysCol.Dictionary<HidUsage, OpenTK.Input.Key> hid2Tk = new SysCol.Dictionary<HidUsage, OpenTK.Input.Key>()
            {
                [HidUsage.ErrorRollOver] = OpenTK.Input.Key.Unknown,
                [HidUsage.PostFail] = OpenTK.Input.Key.Unknown,
                [HidUsage.ErrorUndefined] = OpenTK.Input.Key.Unknown,
                [HidUsage.A] = OpenTK.Input.Key.A,
                [HidUsage.B] = OpenTK.Input.Key.B,
                [HidUsage.C] = OpenTK.Input.Key.C,
                [HidUsage.D] = OpenTK.Input.Key.D,
                [HidUsage.E] = OpenTK.Input.Key.E,
                [HidUsage.F] = OpenTK.Input.Key.F,
                [HidUsage.G] = OpenTK.Input.Key.G,
                [HidUsage.H] = OpenTK.Input.Key.H,
                [HidUsage.I] = OpenTK.Input.Key.I,
                [HidUsage.J] = OpenTK.Input.Key.J,
                [HidUsage.K] = OpenTK.Input.Key.K,
                [HidUsage.L] = OpenTK.Input.Key.L,
                [HidUsage.M] = OpenTK.Input.Key.M,
                [HidUsage.N] = OpenTK.Input.Key.N,
                [HidUsage.O] = OpenTK.Input.Key.O,
                [HidUsage.P] = OpenTK.Input.Key.P,
                [HidUsage.Q] = OpenTK.Input.Key.Q,
                [HidUsage.R] = OpenTK.Input.Key.R,
                [HidUsage.S] = OpenTK.Input.Key.S,
                [HidUsage.T] = OpenTK.Input.Key.T,
                [HidUsage.U] = OpenTK.Input.Key.U,
                [HidUsage.V] = OpenTK.Input.Key.V,
                [HidUsage.W] = OpenTK.Input.Key.W,
                [HidUsage.X] = OpenTK.Input.Key.X,
                [HidUsage.Y] = OpenTK.Input.Key.Y,
                [HidUsage.Z] = OpenTK.Input.Key.Z,
                [HidUsage.D1] = OpenTK.Input.Key.Number1,
                [HidUsage.D2] = OpenTK.Input.Key.Number2,
                [HidUsage.D3] = OpenTK.Input.Key.Number3,
                [HidUsage.D4] = OpenTK.Input.Key.Number4,
                [HidUsage.D5] = OpenTK.Input.Key.Number5,
                [HidUsage.D6] = OpenTK.Input.Key.Number6,
                [HidUsage.D7] = OpenTK.Input.Key.Number7,
                [HidUsage.D8] = OpenTK.Input.Key.Number8,
                [HidUsage.D9] = OpenTK.Input.Key.Number9,
                [HidUsage.D0] = OpenTK.Input.Key.Number0,
                [HidUsage.Enter] = OpenTK.Input.Key.Enter,
                [HidUsage.Escape] = OpenTK.Input.Key.Escape,
                [HidUsage.Backspace] = OpenTK.Input.Key.BackSpace,
                [HidUsage.Tab] = OpenTK.Input.Key.Tab,
                [HidUsage.Space] = OpenTK.Input.Key.Space,
                [HidUsage.Minus] = OpenTK.Input.Key.Minus,
                [HidUsage.Equal] = OpenTK.Input.Key.Plus,
                [HidUsage.LeftBracket] = OpenTK.Input.Key.BracketLeft,
                [HidUsage.RightBracket] = OpenTK.Input.Key.BracketRight,
                [HidUsage.Backslash] = OpenTK.Input.Key.Unknown,
                [HidUsage.Hash] = OpenTK.Input.Key.BackSlash,
                [HidUsage.Semicolon] = OpenTK.Input.Key.Semicolon,
                [HidUsage.Quote] = OpenTK.Input.Key.Quote,
                [HidUsage.Grave] = OpenTK.Input.Key.Grave,
                [HidUsage.Comma] = OpenTK.Input.Key.Comma,
                [HidUsage.Period] = OpenTK.Input.Key.Period,
                [HidUsage.Slash] = OpenTK.Input.Key.Slash,
                [HidUsage.CapsLock] = OpenTK.Input.Key.CapsLock,
                [HidUsage.F1] = OpenTK.Input.Key.F1,
                [HidUsage.F2] = OpenTK.Input.Key.F2,
                [HidUsage.F3] = OpenTK.Input.Key.F3,
                [HidUsage.F4] = OpenTK.Input.Key.F4,
                [HidUsage.F5] = OpenTK.Input.Key.F5,
                [HidUsage.F6] = OpenTK.Input.Key.F6,
                [HidUsage.F7] = OpenTK.Input.Key.F7,
                [HidUsage.F8] = OpenTK.Input.Key.F8,
                [HidUsage.F9] = OpenTK.Input.Key.F9,
                [HidUsage.F10] = OpenTK.Input.Key.F10,
                [HidUsage.F11] = OpenTK.Input.Key.F11,
                [HidUsage.F12] = OpenTK.Input.Key.F12,
                [HidUsage.PrintScreen] = OpenTK.Input.Key.PrintScreen,  // Untested

                // OpenTk triggers OpenTK.Input.Key.Pause for both HidUsage.Pause and HidUsage.ScrollLock.
                // It seems it never raises OpenTK.Input.Key.ScrollLock.
                // We bind OpenTK.Input.Key.Pause to HidUsage.Pause.
                [HidUsage.ScrollLock] = OpenTK.Input.Key.ScrollLock,
                [HidUsage.Pause] = OpenTK.Input.Key.Pause,

                [HidUsage.Insert] = OpenTK.Input.Key.Insert,
                [HidUsage.Home] = OpenTK.Input.Key.Home,
                [HidUsage.PageUp] = OpenTK.Input.Key.PageUp,
                [HidUsage.Delete] = OpenTK.Input.Key.Delete,
                [HidUsage.End] = OpenTK.Input.Key.End,
                [HidUsage.PageDown] = OpenTK.Input.Key.PageDown,
                [HidUsage.ArrowRight] = OpenTK.Input.Key.Right,
                [HidUsage.ArrowLeft] = OpenTK.Input.Key.Left,
                [HidUsage.ArrowDown] = OpenTK.Input.Key.Down,
                [HidUsage.ArrowUp] = OpenTK.Input.Key.Up,
                [HidUsage.NumLock] = OpenTK.Input.Key.NumLock,
                [HidUsage.KeypadDivide] = OpenTK.Input.Key.KeypadDivide,
                [HidUsage.KeypadMultiply] = OpenTK.Input.Key.KeypadMultiply,
                [HidUsage.KeypadMinus] = OpenTK.Input.Key.KeypadMinus,
                [HidUsage.KeypadPlus] = OpenTK.Input.Key.KeypadPlus,
                [HidUsage.KeypadEnter] = OpenTK.Input.Key.KeypadEnter,
                [HidUsage.Keypad1] = OpenTK.Input.Key.Keypad1,
                [HidUsage.Keypad2] = OpenTK.Input.Key.Keypad2,
                [HidUsage.Keypad3] = OpenTK.Input.Key.Keypad3,
                [HidUsage.Keypad4] = OpenTK.Input.Key.Keypad4,
                [HidUsage.Keypad5] = OpenTK.Input.Key.Keypad5,
                [HidUsage.Keypad6] = OpenTK.Input.Key.Keypad6,
                [HidUsage.Keypad7] = OpenTK.Input.Key.Keypad7,
                [HidUsage.Keypad8] = OpenTK.Input.Key.Keypad8,
                [HidUsage.Keypad9] = OpenTK.Input.Key.Keypad9,
                [HidUsage.Keypad0] = OpenTK.Input.Key.Keypad0,
                [HidUsage.KeypadPeriod] = OpenTK.Input.Key.KeypadPeriod,

                // OpenTk triggers OpenTK.Input.Key.Comma for both HidUsage.NonUsBackslashAndPipe and HidUsage.Comma.
                // We bind it to HidUsage.Comma.
                [HidUsage.NonUsBackslashAndPipe] = OpenTK.Input.Key.Unknown,

                [HidUsage.Application] = OpenTK.Input.Key.WinLeft,  // Untested
                [HidUsage.Power] = OpenTK.Input.Key.Unknown,        // Could this be OpenTK.Input.Key.Sleep?
                [HidUsage.KeypadEquals] = OpenTK.Input.Key.Unknown,
                [HidUsage.F13] = OpenTK.Input.Key.F13,              // Untested
                [HidUsage.F14] = OpenTK.Input.Key.F14,              // Untested
                [HidUsage.F15] = OpenTK.Input.Key.F15,              // Untested
                [HidUsage.F16] = OpenTK.Input.Key.F16,              // Untested
                [HidUsage.F17] = OpenTK.Input.Key.F17,              // Untested
                [HidUsage.F18] = OpenTK.Input.Key.F18,              // Untested
                [HidUsage.F19] = OpenTK.Input.Key.F19,              // Untested
                [HidUsage.F20] = OpenTK.Input.Key.F20,              // Untested
                [HidUsage.F21] = OpenTK.Input.Key.F21,              // Untested
                [HidUsage.F22] = OpenTK.Input.Key.F22,              // Untested
                [HidUsage.F23] = OpenTK.Input.Key.F23,              // Untested
                [HidUsage.F24] = OpenTK.Input.Key.F24,              // Untested
                [HidUsage.Execute] = OpenTK.Input.Key.Unknown,
                [HidUsage.Help] = OpenTK.Input.Key.Unknown,
                [HidUsage.Menu] = OpenTK.Input.Key.Menu,
                [HidUsage.Select] = OpenTK.Input.Key.Unknown,
                [HidUsage.Stop] = OpenTK.Input.Key.Unknown,
                [HidUsage.Again] = OpenTK.Input.Key.Unknown,
                [HidUsage.Undo] = OpenTK.Input.Key.Unknown,
                [HidUsage.Cut] = OpenTK.Input.Key.Unknown,
                [HidUsage.Copy] = OpenTK.Input.Key.Unknown,
                [HidUsage.Paste] = OpenTK.Input.Key.Unknown,
                [HidUsage.Find] = OpenTK.Input.Key.Unknown,
                [HidUsage.Mute] = OpenTK.Input.Key.Unknown,
                [HidUsage.VolumeUp] = OpenTK.Input.Key.Unknown,
                [HidUsage.VolumeDown] = OpenTK.Input.Key.Unknown,
                [HidUsage.LockingCapsLock] = OpenTK.Input.Key.Unknown,
                [HidUsage.LockingNumLock] = OpenTK.Input.Key.Unknown,
                [HidUsage.LockingScrollLock] = OpenTK.Input.Key.Unknown,
                [HidUsage.KeypadComma] = OpenTK.Input.Key.Unknown,
                [HidUsage.KeypadEqualAS400] = OpenTK.Input.Key.Unknown,
                [HidUsage.International1] = OpenTK.Input.Key.Unknown,
                [HidUsage.International2] = OpenTK.Input.Key.Unknown,
                [HidUsage.International3] = OpenTK.Input.Key.Unknown,
                [HidUsage.International4] = OpenTK.Input.Key.Unknown,
                [HidUsage.International5] = OpenTK.Input.Key.Unknown,
                [HidUsage.International6] = OpenTK.Input.Key.Unknown,
                [HidUsage.International7] = OpenTK.Input.Key.Unknown,
                [HidUsage.International8] = OpenTK.Input.Key.Unknown,
                [HidUsage.International9] = OpenTK.Input.Key.Unknown,
                [HidUsage.Lang1] = OpenTK.Input.Key.Unknown,
                [HidUsage.Lang2] = OpenTK.Input.Key.Unknown,
                [HidUsage.Lang3] = OpenTK.Input.Key.Unknown,
                [HidUsage.Lang4] = OpenTK.Input.Key.Unknown,
                [HidUsage.Lang5] = OpenTK.Input.Key.Unknown,
                [HidUsage.Lang6] = OpenTK.Input.Key.Unknown,
                [HidUsage.Lang7] = OpenTK.Input.Key.Unknown,
                [HidUsage.Lang8] = OpenTK.Input.Key.Unknown,
                [HidUsage.Lang9] = OpenTK.Input.Key.Unknown,
                [HidUsage.AlternateErase] = OpenTK.Input.Key.Unknown,
                [HidUsage.SysReq] = OpenTK.Input.Key.Unknown,
                [HidUsage.Cancel] = OpenTK.Input.Key.Unknown,
                [HidUsage.Clear] = OpenTK.Input.Key.Unknown,
                [HidUsage.Prior] = OpenTK.Input.Key.Unknown,
                [HidUsage.Return] = OpenTK.Input.Key.Unknown,
                [HidUsage.Separator] = OpenTK.Input.Key.Unknown,
                [HidUsage.Out] = OpenTK.Input.Key.Unknown,
                [HidUsage.Oper] = OpenTK.Input.Key.Unknown,
                [HidUsage.ClearAgain] = OpenTK.Input.Key.Unknown,
                [HidUsage.CrSel] = OpenTK.Input.Key.Unknown,
                [HidUsage.ExSel] = OpenTK.Input.Key.Unknown,
                // A5-AF RESERVED
                [HidUsage.Keypad00] = OpenTK.Input.Key.Unknown,
                [HidUsage.Keypad000] = OpenTK.Input.Key.Unknown,
                [HidUsage.ThousandsSeparator] = OpenTK.Input.Key.Unknown,
                [HidUsage.DecimalSeparator] = OpenTK.Input.Key.Unknown,
                [HidUsage.CurrencyUnit] = OpenTK.Input.Key.Unknown,
                [HidUsage.CurrencySubUnit] = OpenTK.Input.Key.Unknown,
                [HidUsage.KeypadParenthesisLeft] = OpenTK.Input.Key.Unknown,
                [HidUsage.KeypadParenthesisRight] = OpenTK.Input.Key.Unknown,
                [HidUsage.KeypadBraceLeft] = OpenTK.Input.Key.Unknown,
                [HidUsage.KeypadBraceRight] = OpenTK.Input.Key.Unknown,
                [HidUsage.KeypadTab] = OpenTK.Input.Key.Unknown,
                [HidUsage.KeypadBackspace] = OpenTK.Input.Key.Unknown,
                [HidUsage.KeypadA] = OpenTK.Input.Key.Unknown,
                [HidUsage.KeypadB] = OpenTK.Input.Key.Unknown,
                [HidUsage.KeypadC] = OpenTK.Input.Key.Unknown,
                [HidUsage.KeypadD] = OpenTK.Input.Key.Unknown,
                [HidUsage.KeypadE] = OpenTK.Input.Key.Unknown,
                [HidUsage.KeypadF] = OpenTK.Input.Key.Unknown,
                [HidUsage.KeypadXor] = OpenTK.Input.Key.Unknown,
                [HidUsage.KeypadLogicalAnd] = OpenTK.Input.Key.Unknown,
                [HidUsage.KeypadPercent] = OpenTK.Input.Key.Unknown,
                [HidUsage.KeypadLessThan] = OpenTK.Input.Key.Unknown,
                [HidUsage.KeypadGreaterThan] = OpenTK.Input.Key.Unknown,
                [HidUsage.KeypadAnd] = OpenTK.Input.Key.Unknown,
                [HidUsage.KeypadAndAnd] = OpenTK.Input.Key.Unknown,
                [HidUsage.KeypadOr] = OpenTK.Input.Key.Unknown,
                [HidUsage.KeypadOrOr] = OpenTK.Input.Key.Unknown,
                [HidUsage.KeypadColon] = OpenTK.Input.Key.Unknown,
                [HidUsage.KeypadHash] = OpenTK.Input.Key.Unknown,
                [HidUsage.KeypadSpace] = OpenTK.Input.Key.Unknown,
                [HidUsage.KeypadAt] = OpenTK.Input.Key.Unknown,
                [HidUsage.KeypadExclamation] = OpenTK.Input.Key.Unknown,
                [HidUsage.KeypadMemoryStore] = OpenTK.Input.Key.Unknown,
                [HidUsage.KeypadMemoryRecall] = OpenTK.Input.Key.Unknown,
                [HidUsage.KeypadMemoryClear] = OpenTK.Input.Key.Unknown,
                [HidUsage.KeypadMemoryAdd] = OpenTK.Input.Key.Unknown,
                [HidUsage.KeypadMemorySubtract] = OpenTK.Input.Key.Unknown,
                [HidUsage.KeypadMemoryMultiply] = OpenTK.Input.Key.Unknown,
                [HidUsage.KeypadMemoryDivide] = OpenTK.Input.Key.Unknown,
                [HidUsage.KeypadSign] = OpenTK.Input.Key.Unknown,
                [HidUsage.KeypadClear] = OpenTK.Input.Key.Unknown,
                [HidUsage.KeypadClearEntry] = OpenTK.Input.Key.Unknown,
                [HidUsage.KeypadBinary] = OpenTK.Input.Key.Unknown,
                [HidUsage.KeypadOctal] = OpenTK.Input.Key.Unknown,
                [HidUsage.KeypadDecimal] = OpenTK.Input.Key.Unknown,
                [HidUsage.KeypadHexadecimal] = OpenTK.Input.Key.Unknown,
                // DE-DF RESERVED
                [HidUsage.ControlLeft] = OpenTK.Input.Key.ControlLeft,
                [HidUsage.ShiftLeft] = OpenTK.Input.Key.ShiftLeft,
                [HidUsage.AltLeft] = OpenTK.Input.Key.AltLeft,
                [HidUsage.GuiLeft] = OpenTK.Input.Key.Unknown,
                [HidUsage.ControlRight] = OpenTK.Input.Key.ControlRight,
                [HidUsage.ShiftRight] = OpenTK.Input.Key.ShiftRight,
                [HidUsage.AltRight] = OpenTK.Input.Key.AltRight,
                [HidUsage.GuiRight] = OpenTK.Input.Key.Unknown,
                // E8-FFFF RESERVED
            };
        }
    }
}
